### ISSUE TITLE
production - check redirect links when "items" are deleted

### ISSUE THREAD

**Issue by glw** [fpdcc/ccfp-asset-dashboard#217]
There has been anecdotal mentions that after deleting of phase funding the redirect to the wrong project page. So when removing/deleting "items" (phases, phase funding, etc.) links to redirect users should be double checked.

**Comment by smcalilly** [comment]
@xmedr For this issue, my suspicion is that the redirect url is being created based on the id of the item that is deleted instead of the id of the project.

So like, the urls might look like this:
- project detail: `/projects/85/`
- phase for that project: `/projects/phases/edit/126/`
- phase funding for that project's phase: `/projects/phases/38/funding/update/`

Whenever a user "deletes" the phase or phase funding, what key is used to build the redirect url? It should be the project key (`85` in the above project url example). You might need to hook into the [PhaseDeleteView](https://github.com/fpdcc/ccfp-asset-dashboard/blob/master/asset_dashboard/views.py#L285) and the [FundingStreamDeleteView](https://github.com/fpdcc/ccfp-asset-dashboard/blob/master/asset_dashboard/views.py#L349) to set the correct id in the redirect url.

**Comment by smcalilly** [comment]
We're not able to recreate this. Is it possible that this is a duplicate issue @glw? We've dealt with this in the past and fixed via this issue #137.
