### ISSUE TITLE
CIP portfolio asset summary

### ISSUE THREAD

**Issue by glw** [fpdcc/ccfp-asset-dashboard#219]
Create a way to export an asset summary by portfolio. Whether that be an image of a map and/or adding the asset ID's to the CIP export. This way users can get a visual location representation of their projects in a particular portfolio.

**Comment by smcalilly** [comment]
I can see a few ways to do this. We should ask them how they want this.

Would we want to include this in the CIP export or create a separate export for this?

**Comment by jim-z** [comment]
@smcalilly @xmedr this is primarily a means for us GIS folks to be able to easily create maps that typically get included in the CIP to display project locations .  It can be a separate export more catered toward our mapping needs or just included as asset IDs with the CIP Planner csv export that we would then join back to our geometry and export again on our end to create custom maps.

**Comment by xmedr** [comment]
@jim-z Cool, in the example below I have all the asset IDs for each phase in the portfolio populating an "assets" column. It's a small dataset since it's just my local machine, but what do you think of this?

[Xavier-Test-2023-08-03.csv](https://github.com/fpdcc/ccfp-asset-dashboard/files/12252744/Xavier-Test-2023-08-03.csv)

![image](https://github.com/fpdcc/ccfp-asset-dashboard/assets/114717958/1f2dd8c5-d7eb-46c5-8014-6956309bd01e)

**Comment by smcalilly** [comment]
i'm going to add this to the CIP export in the changes i make in #257

**Comment by jim-z** [comment]
Yeah, I think this works for listing assets...only potential issue I see is needing to discern between asset type (i.e. building, trail, picnic grove).  It might be easy enough to determine what is what base don the project type/section but would be easier on us if assets were broken into a separate column for type:
![image](https://github.com/fpdcc/ccfp-asset-dashboard/assets/11774880/14a38ea1-0c6c-4f96-abbe-de088a76af9d)
