### ISSUE TITLE
Add ability to select multiple projects in CIP Planner

### ISSUE THREAD

**Issue by jim-z** [fpdcc/ccfp-asset-dashboard#258]
Currently have to add projects one at a time to build portfolio.  If you have sorted based on year, etc. you have to resort every time you add a new project.  Adding the ability to select multiple projects to add to portfolio would make this much less cumbersome.

**Comment by xmedr** [comment]
Hey @jim-z, how would you feel about us adding a way to have the sort persist between additions? I have an example of that change below with the Quarter sort persisting. This way the process stays the same just with a quality of life change. Or would you want to stick to selecting multiple projects? No worries either way!

![ezgif-3-1aec6cf75e](https://github.com/fpdcc/ccfp-asset-dashboard/assets/114717958/77411f9f-24dd-4688-b74b-8b0960943448)

**Comment by jim-z** [comment]
@xmedr this might suffice if it is easier to implement for the time being.  One other related issue I forgot to mention is that my sort results displayed on multiple pages.  When I added a project from page 3 of 5, I would also get forced back to page 1 of 5 and then have to navigate back to where I left off by remembering what projects were above and below the one I had just added.

**Comment by xmedr** [comment]
@jim-z Ah you're right I see that happening for me too, thanks for flagging! I've got another quick change in there now that lets the page number persist between selections as well. It also allows you to change the sort/filter and stay on the same page. Got another demo of that here, what do you think?

(Note: the tables here show 5 results per page, just so that I have more pages to flip through for testing/demoing)
![page-persist](https://github.com/fpdcc/ccfp-asset-dashboard/assets/114717958/3e674896-d44f-46b5-8c6f-7b98e8ca657f)

These were super quick changes, so if we wanted to explore the multiple selection method as well I can chat with the others to see what they think!
