### ISSUE TITLE
Update models to allow a link between a GIS asset and a project

### ISSUE THREAD

**Issue by fgregg** [fpdcc/ccfp-asset-dashboard#62]
Key question:

Do we want to have a direct link between the project and the GIS object, or do we want to make a copy of the GIS object when we make a link. 

Benefits of direct link.

1. One fewer thing to get out of synch. 
2. It is going to probably surprise the user if an object they attached to a project disappears or dramatically changes.

Probably the best thing to do is to make a copy, and to have a check whether the object has changed or disappeared. If so, prompt the user to do a refresh the data or ignore.

Making a copy is also going to be good because we are going to want to make custom GIS objects that are just sections of bigger GIS objects. If we make copies, we can just store the part that we want instead of a complicated set of objects necessary to filter the original GIS object.

Having local copies will probably also make it a lot faster to do some SQL objects.

**Comment by smcalilly** [comment]
Ok, this makes more sense. I was thinking about the objects change happening on our UI, where one user is updating the assets for a project while another user is looking at the same project on another device. But this is asking about how to deal with changes from the Forest Preserve's GIS database.

**Comment by smcalilly** [comment]
@fgregg With the approach of a copy, would we need a new model and what would the model fields be?

**Comment by fgregg** [comment]
Yes, we would.

Probably would be something like

```
LocalAsset
    parent_id = foreign_key_to_original_asset
    filtered = Bool # is this a subset of the original obj
    last_updated_at # to check if the parent is newer
    geom # a copy of geom, if filtered, then just the filtered piece of the geom
```

**Comment by smcalilly** [comment]
@fgregg And would there a be foreign key so it's related to a `Phase`?

**Comment by fgregg** [comment]
that could be a good way to do it, yes!

**Comment by smcalilly** [comment]
I asked Garret what tables we need to search, and on what fields.

- `buildings` table
  - search by `fpd_uid` and `building_name`
- `trails`
  - search: "a trail subsystem will get them close enough to where they need to find what they're looking for" (rough quote)
- `pointsofinterest`
  - similar to buildings, search for name
  - filter on `poi_info_id == poi_info_id_group`
- `parking_lots`
  - need to get clarification about what fields we need to search
- `picnicgroves`
  - this table has a `fpd_uid`, but we need to double check that's the right field for searching
- `signage`
  - this will require some filtering because it's a catch all for different types of points (like benches, etc) -- need clarification
