### ISSUE TITLE
 Design user interface for associating GIS assets with project

### ISSUE THREAD

**Issue by fgregg** [fpdcc/ccfp-asset-dashboard#63]
Design interface to select assets, associate them with project, and remove those associations

1. should include map interface and textual interface

**Comment by smcalilly** [comment]
@fgregg I added my thoughts in this Google Doc so you can easily comment on some of the questions raised: https://docs.google.com/document/d/1YZWf0PtqQsibSBQ7SiqbQBDlZdCrUAJgLKHy5_UH8mE/edit?usp=sharing

**Comment by smcalilly** [comment]
@fgregg here's the first draft of designing the "normal view" and "edit view" interface, based on our discussion: https://app.moqups.com/oyzaWsCDbsZ7xXShLNvzgbpzpBoQ8D1s/view/page/ad64222d5

this also includes work for #65

**Comment by smcalilly** [comment]
Two things from our most recent meeting with Garret:

## search interface
We'll need to come up with a simple and user friendly way to communicate the different ways of searching the different tables, based on this comment: https://github.com/fpdcc/ccfp-asset-dashboard/issues/62#issuecomment-1013240850

The best I can think of so far -- have a dropdown for the different tables and then populate a help message in the search bar. For example, a user selects buildings and in the search bar some text says "search by fpd_uid or building_name". This would be easy to implement but I'm not sure about the user experience. @fgregg @hancush if y'all have any ideas, let me know. 

## asset selection
We'll need to improve the existing selection feature from PR #93. Garret said they'll need to be able to select sections of trails with a custom polygon rather than the rectangle selector that we have. They'll also need a way to unselect a selection. And they'll need to be able to select by clicking on an asset, rather than only dragging a polygon. This all might need to be added to a new issue so we can track the work? There are a few pieces of work implied here.
